### ISSUE TITLE
signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is invalid error

### ISSUE THREAD

**Issue by slester** [BlackArch/blackarch#1594]
After a `pacaur -Syyu`:

```
error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch
Developer) <noptrix@nullsecurity.net>" is invalid
error: failed to update blackarch (invalid or corrupted database (PGP
signature))
```

**Comment by noptrix** [comment]
@ikstream Hi, thanks for reporting this. Can you switch temporarily to blackarch.org/* in your pacman.conf and simply retry: `yes |pacman -Scc && pacman -Syyu' please and let me know

**Comment by noptrix** [comment]
should be fixed

**Comment by ikstream** [comment]
@noptrix wasn't me ;)

**Comment by dantopa** [comment]
Hi, I'm having the same problem- What I'm supposed to do when switching temporarly to blackarch.org/* ? Can you be more specifically? Thanks

**Comment by ryukinix** [comment]
I have the same problem here...

**Comment by feralgibbons** [comment]
Hate to get my necro on, but this issue is still present, and is still a problem w/ mirrors syncing properly (harking back at least as far as #959.)  Having just iterated through a chunk of the mirrors on the list and getting exactly the same results described here by @slester, comment out everything in /etc/pacman.d/mirrorlist, add Server = https://www.blackarch.org/ at the bottom, run pacman -Scc, pacman-key --refresh-keys and finally pacman -Syy and you should be good.  Caveat: "Hey man, it worked for me."

**Comment by myGod0rz** [comment]
I just "rm /var/lib/pacman/sync/blackarch.db.sig" after "pacman -Syy".
Works well for me.

**Comment by Asky-M** [comment]
> I just "rm /var/lib/pacman/sync/blackarch.db.sig" after "pacman -Syy".
> Works well for me.

it's working to me. thanks.
