### ISSUE TITLE
Hey ther is a Problem with  signature from "Levon 'noptrix' Kayan (BlackArch Developer)

### ISSUE THREAD

**Issue by darkstar999** [BlackArch/blackarch#883]
sudo pacman -Syyu blackarch-keyring
Fehler: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is invalid

I couldn't fix it because /etc/pacman.conf

SigLevel= Never

sudo pacman -S blackarch-keyring

keeps no effect because   Warnung: blackarch-keyring-20140118-3 ist aktuell -- Reinstalliere

Please fix it!

**Comment by noptrix** [comment]
fixed. just re-run pacman -Syyu

**Comment by darkstar999** [comment]
Perfect THX

**Comment by fnk0c** [comment]
[franco@Arch ~]$ sudo pacman -Syyu 
    error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is invalid
    :: Synchronizing package databases...
  
     blackarch               1348,0 KiB   105K/s 00:13 [######################] 100%
     blackarch.sig            543,0   B  0,00B/s 00:00 [######################] 100%
     error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is invalid
     error: failed to update blackarch (invalid or corrupted database (PGP signature))
     error: database 'blackarch' is not valid (invalid or corrupted database (PGP signature))

Fixed inserting SigLevel = Never on pacman.conf, but thought that would be good to inform you

**Comment by aancw** [comment]
It's happened to me yesterday.
Try to mv ~/.gnupg/ ~/.gnupg-old

and update again. Hope will be help

**Comment by fnk0c** [comment]
Worked! Thx, bro!

**Comment by Silur** [comment]
it happened again, refresh-keys say `gpg: key 67D8BDF42AD93F4E: "Levon 'noptrix' Kayan (BlackArch Master) <noptrix@nullsecurity.net>" not changed`
Please @noptrix..... :)

**Comment by Silur** [comment]
Sorry I have to mention here that it still happens for me on every boot, only solution is to run `-Syyu` every time before doing something with yaourt/pacman
Can someone confirm so I can be sure about this key mismatch only happening to me locally?

**Comment by aancw** [comment]
@Silur how about this?

```
pacman-key --init
pacman-key --populate archlinux
```

**Comment by chocopowwwa** [comment]
#1594

**Comment by chocopowwwa** [comment]
#1594

**Comment by chocopowwwa** [comment]
update the database?
```sudo pacman -Syy``` solved issue for me

**Comment by UltraBlackLinux** [comment]
The problem is back - termuxarch
Didn't help

**Comment by ikstream** [comment]
Please open a new issue with all the relevant info

**Comment by steve01101** [comment]
I have the same problem. i read the whole chat, nothing worked for me.

`# pacman -Syyu
errore: blackarch: la firma di "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" ha un'affidabilità sconosciuta
:: Sincronizzazione dei database in corso...
 core                                                 137,6 KiB   101 KiB/s 00:01 [##############################################] 100%
 extra                                               1567,3 KiB  1114 KiB/s 00:01 [##############################################] 100%
 community                                              5,9 MiB  2,95 MiB/s 00:02 [##############################################] 100%
 multilib                                             148,4 KiB   190 KiB/s 00:01 [##############################################] 100%
 blackarch                                              3,6 MiB  3,77 MiB/s 00:01 [##############################################] 100%
errore: blackarch: la firma di "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" ha un'affidabilità sconosciuta
errore: failed to synchronize all databases (il database non è valido oppure è corrotto (firma PGP))
`
